#ddev-generated

# Fix cache directory permissions for non-root user
RUN bash -eux <<'SHELL'
DIRS=(
	.cache
	.bashrc.d
)
for rel in "${DIRS[@]}"; do
	dir="/home/$username/$rel"
	mkdir -p "$dir"
	chown "$username:" "$dir"
done
SHELL
