#ddev-generated
services:
  web:
    volumes:
      - "$HOME/.ssh:$HOME/.ssh"
      - "./homemounts/.local:$HOME/.local"
      - "$HOME/.local:$HOME/.local"
      - "$HOME/.gitconfig:$HOME/.gitconfig"
      # - "$HOME/.local/share/pnpm:$HOME/.local/share/pnpm"
      # For mounted files, parent directories should be listed in the file `web-build/Dockerfile.murz` to fix permissions issues.
      - "$HOME/.config/gh:$HOME/.config/gh"
      - "$HOME/.config/pnpm:$HOME/.config/pnpm"
      # - "$HOME/.cache/pnpm:$HOME/.cache/pnpm"
      - "$HOME/.cache:$HOME/.cache"
      ## A workaround to fix the directory owner to not be root.
      # - "./ddev-murz/.bashrc.d:$HOME/.bashrc.d"
      - "$HOME/.bashrc.d/murz.local.sh:$HOME/.bashrc.d/murz.local.sh"
