#ddev-generated
services:
  web:
    volumes:
      - "./homemounts/.vscode-server:$HOME/.vscode-server"
      - "$HOME/.cache/ddev/vscode/containers-bin:$HOME/.vscode-server/bin"
      - "$HOME/.cache/ddev/vscode/extensionsCache:$HOME/.vscode-server/extensionsCache"
      - "$HOME/.ssh:$HOME/.ssh"
      - "./homemounts/.local:$HOME/.local"
      - "$HOME/.local/bin:$HOME/.local/bin"
      - "$HOME/.gitconfig:$HOME/.gitconfig"
      - "$HOME/.local/share/pnpm:$HOME/.local/share/pnpm"
      # For mounted files, parent directories should be listed in the file `web-build/Dockerfile.murz` to fix permissions issues.
      - "$HOME/.config/pnpm:$HOME/.config/pnpm"
      - "$HOME/.cache/pnpm:$HOME/.cache/pnpm"
      - "$HOME/.bashrc.d/murz.local.sh:$HOME/.bashrc.d/murz.local.sh"
